### ISSUE TITLE
How could a HWDB be added?

### ISSUE THREAD

**Issue by Icenowy** [gizmo98/hwdb-converter#1]
T-Head TH1520 SoC's kernel driver contains a HWDB file only for their specific configuration of GC620, as seen at https://github.com/revyos/thead-kernel/blob/lpi4a/drivers/gpu-viv/hal/kernel/inc/gc_feature_database.h .

**Comment by gizmo98** [comment]
I have added thead hwdb header file. You can find the new hwdb entry in following commit:
https://github.com/gizmo98/hwdb-converter/commit/e2f09f4fe2417892d9ddd4c873f26d7434066e64

**Comment by Icenowy** [comment]
Thanks!
